### ISSUE TITLE
Readme: talk about non-photorealistic rendering

### ISSUE THREAD

**Issue by pforhan** [Rezmason/drivey#12]
One of the fascinating aspects of drivey is how not-real it is but still captures that essence of reality.  The readme hints at this a bit already.

The original web page talked about this a bit, some of which captured at http://frugalgames.com/10/04/4/drivey -- sounds like there was also some audio commentary at some point but I can't get it to load.

**Comment by Rezmason** [comment]
Mark told me back in March, `"...there is proprietary code for shape rendering (optimized for quadratic curves as used in TrueType fonts)"`. So at least some of it is quadratic beziers.

His video with audio commentary is just gone, along with the old Google Video website, from the looks of it. But he has got older versions of the demo online, and I've found bugs in version 0.02 that he fixed by 0.1.0, that offer a glimpse into the way the engine works.

![image](https://user-images.githubusercontent.com/1041555/46880978-0e980b00-cdff-11e8-97f1-7e81c7ceb813.png)

Same geometry, vantage point, but with different vertical positions. Most of these lines are parts of cars. (In v0.02, cars are the word "CAR" extruded in 3D, so they have lots of curves.) A few of the lines are the road geometry. The lines are usually vertical, but are occasionally angled- and the angles aren't consistent from frame to frame, they flicker. _(My guess is the angled lines were the result of a precision-sensitive bug, where very small numbers are expected to be exact but they're not. And applying perspective projection to geometry sounds to me like a possible cause for precision sensitivity.)_

![image](https://user-images.githubusercontent.com/1041555/46881153-74849280-cdff-11e8-9838-fca24ca4b1ab.png)

Again, same vantage point, same geometry, different vertical positions. The buildings in v0.02's city level don't reach the ground, and if you rise above their lowest point, they kind of invert. We can see that their silhouettes are constructed from vertical lines attached to a curve that represents half their top-down profile.

Also note that all of the up-down lines are parallel, all of the time.

My current theory is, when Drivey draws something like a rail, it first applies perspective to the rail shape at its start and end heights, and then some function compares the two shapes and decides which pieces of the top and bottom curves to draw, with straight lines inserted into the combined path. When the top or bottom shape is outside certain ranges, v0.0.2 glitches, and draws lines that are too tall, or chooses the wrong "side" of a curve to construct the silhouette.

**Comment by Rezmason** [comment]
Finally wrote up [MY OTHER CAR IS A BÉZIER](https://github.com/Rezmason/drivey/blob/master/MY_OTHER_CAR_IS_A_BEZIER.md). I didn't dive too deep into the rendering techniques, since the original code is closed source and my speculation doesn't have much significance. Instead I wrote what I'm sure of, and focused on the kind of world Drivey was born into.

**Comment by Rezmason** [comment]
Oh, and at least some audio commentary is still available in [this WMV](http://web.archive.org/web/20071013193440/http://intepid.com/stuff/intepid.2005-05-08.drivey.256.wmv) I found on the Internet Archive.

**Comment by pforhan** [comment]
It reads nicely, thanks.
