### ISSUE TITLE
Make adjustments to one switch and eye gaze controls

### ISSUE THREAD

**Issue by oneswitch** [Rezmason/drivey#14]
Really enjoying the new additions. However, I do find the adjustment in speed, and also swapping side of the road is now too gradual. When I change the speed from fastest to slowest, I'm not sure if it's doing anything for a while. 

I also much preferred the more rapid lane changing when swapping from left to right-side drive. If you turn the dash off, that's a really nice one-switch method of driving for those with much less accurate control. It now feels much less responsive. Not such a strong cause and effect response.

**Comment by Rezmason** [comment]
New idea: one-switch and eye gaze on autopilot will adjust the car's lane, instead of operate the steering wheel. While the wheel directly affects the car's direction, the lane affects where the autopilot drives to. This is more or less what clicking the lane button already does; it will work with, rather than against, the autopilot.

**Comment by Rezmason** [comment]
It won't be as sudden as the lane changing code, but the new control scheme hopefully makes for a more interesting driving experience for one-switch users on autopilot
